# Generated by Django 4.2.5 on 2023-09-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desease',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='symptoms',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
