# Generated by Django 4.2.5 on 2023-09-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_desease_name_alter_symptoms_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desease',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='symptoms',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
